include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_empty_else: true
    prefer_void_to_null: true
    unrelated_type_equality_checks: true
    valid_regexps: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_return_types_on_setters: true
    eol_at_end_of_file: true
    exhaustive_cases: true
    file_names: true
